---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    # Telegraf Configuration

    [global_tags]
    [agent]
      interval = "1s"
      flush_interval = "1s"


    ###############################################################################
    #                            OUTPUT PLUGINS                                   #
    ###############################################################################

    # Configuration for sending metrics to InfluxDB
    [[outputs.influxdb]]
      urls = ["http://influx-service:8086"]
      database = "{{INFLUXDB_DB}}"
      skip_database_creation = false

    ###############################################################################
    #                            INPUT PLUGINS                                   #
    ###############################################################################
   
    # Read metrics from MQTT topic(s)

    [[inputs.mqtt_consumer]]

      servers = ["mqtt-service:1883"]
      name_override = "mash"
      topics = ["/brewery/mash_temp"]
      data_format = "value"
      data_type = "float"

    [[inputs.mqtt_consumer]]

      servers = ["mqtt-service:1883"]
      name_override = "keezer"
      topics = ["/brewery/keezer_temp"]
      data_format = "value"
      data_type = "float"

    [[inputs.mqtt_consumer]]

      servers = ["mqtt-service:1883"]
      name_override = "topwater"
      topics = ["/brewery/topwater_temp"]
      data_format = "value"
      data_type = "float"

    [[inputs.mqtt_consumer]]

      servers = ["mqtt-service:1883"]
      name_override = "wort"
      topics = ["/brewery/wort_temp"]
      data_format = "value"
      data_type = "float"

    [[inputs.mqtt_consumer]]

      servers = ["mqtt-service:1883"]
      name_override = "fermenter"
      topics = ["/brewery/fermenter_temp"]
      data_format = "value"
      data_type = "float"